const HTML_NODE_FIELD_COMMENT_ID = '_';
const HTML_NODE_FIELD_DATE = '-';
const HTML_NODE_FIELD_SHOWN = '__';
const HTML_NODE_FIELD_REPLIES_COUNT = '_-';
const HTML_NODE_FIELD_OLDEST_REPLY_ID = '_a';
const HTML_NODE_FIELD_NEWEST_REPLY_ID = '_b';
