version: '3.3'

services:
    mongo:
        image: mongo:4.2.6-bionic
        networks:
            - commentator
        restart: always
        volumes:
            - ./mongo-data/:/data/db/:rw
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=r_xAf5RPdK7ZOqnYFjvcp57tPKVbx3bc7Uu
        command: --quiet
    api:
        image: docker.marsgpl.com/commentator/api:latest
        networks:
            - commentator
        restart: always
        ports:
            - 127.0.0.1:42080:80

networks:
    commentator:
        external:
            name: commentator
